//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public string username { get; set; }
        public string machinename { get; set; }
        public string machineIp { get; set; }
        public string Date { get; set; }
        public int id { get; set; }
    }
}
